spring.application.name=filenet
#Server port
server.port=8080

# File upload size limits
# Max size per single file
spring.servlet.multipart.max-file-size=10240GB
spring.servlet.multipart.max-request-size=10240GB

# FileNet connection settings
filenet.uri=http://192.168.1.40:9080/wsi/FNCEWS40MTOM/
filenet.username=wasadmin
filenet.password=sarasu10
filenet.objectstore=test
